### ISSUE TITLE
Fail run kepler-sdk@0.11.0 from npm

### ISSUE THREAD

**Issue by Lokman928** [spruceid/kepler-sdk#47]
When I install kepler-sdk from npm, and develop a simple application on this, some error shows below:
```ERROR in ./node_modules/kepler-sdk/dist/tzString.js 51:19-48
Module not found: Error: Can't resolve '@airgap/beacon-sdk' in '/Users/thomas/ProgrammingWorkspace/kepler-sdk-testing/node_modules/kepler-sdk/dist'
 @ ./node_modules/kepler-sdk/dist/index.js 59:17-38
 @ ./src/main.ts 39:19-40

ERROR in ./node_modules/kepler-sdk/dist/zcap.js 53:23-58
Module not found: Error: Can't resolve '@spruceid/zcap-providers' in '/Users/thomas/ProgrammingWorkspace/kepler-sdk-testing/node_modules/kepler-sdk/dist'
 @ ./node_modules/kepler-sdk/dist/index.js 55:13-30
 @ ./src/main.ts 39:19-40

ERROR in ./node_modules/kepler-sdk/dist/zcap.js 54:13-28
Module not found: Error: Can't resolve 'siwe' in '/Users/thomas/ProgrammingWorkspace/kepler-sdk-testing/node_modules/kepler-sdk/dist'
Did you mean './siwe'?
```

**Comment by cobward** [comment]
Thanks for raising the issue. Kepler and the sdk have undergone a lot of changes in the past few months, which means that v.0.11.0 will not work with the current version of Kepler. If you wish to try out Kepler at the moment, I would suggest using the `main` branches of both `kepler` and `kepler-sdk`.

If you still want to try getting v.0.11 working, I believe the issue is that those three dependencies should be listed in `kepler-sdk`'s package.json as peer dependencies. Installing the following dependencies may fix the issue:
```bash
npm install @airgap/beacon-sdk@2.2.3 @spruceid/zcap-providers@0.1.1 siwe@0.1.4
```
